name: jack roberts
favicon: null
layout_spectrum: 0.88986
typography_spectrum: 0.75871
title: jackroberts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7b8b3'
    - '#555d5f'
    - '#112530'
    - '#fbded0'
    - '#ca7f73'
  brandStrength: 0.8916630139574409
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
