name: jack roberts
favicon: null
layout_spectrum: 0.8231829234864563
typography_spectrum: 0.18950637080706656
title: jackroberts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8916630139574409
  lightness: 0.7287733585108072
  saturation: 0.7838877004105598
  rhythmicContrast: 0.4579325879458338
purpose: []
