name: jack roberts
favicon: null
layout_spectrum: 0.74172
typography_spectrum: 0.75871
title: jack roberts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7b8b3'
    - '#555d5f'
    - '#112530'
    - '#fbded0'
    - '#ca7f73'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
